version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@elastic/elastic-eslint-config-kibana"
      - dependency-name: "@elastic/eslint-import-resolver-kibana"
